/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    IconKantoku: typeof import('./src/components/icons/IconKantoku.vue')['default']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCard: typeof import('@varlet/ui')['_CardComponent']
    VarCell: typeof import('@varlet/ui')['_CellComponent']
    VarChip: typeof import('@varlet/ui')['_ChipComponent']
    VarCol: typeof import('@varlet/ui')['_ColComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarPaper: typeof import('@varlet/ui')['_PaperComponent']
    VarRow: typeof import('@varlet/ui')['_RowComponent']
  }
}
